# Mengatur versi Kubernetes API yang digunakan untuk membuat object dari manifest yaitu v1
apiVersion: v1
# Mengatur jenis object yang dibuat yaitu Secret
kind: Secret
# Mengatur nama dari object Secret yang dibuat yaitu mongo-secret
# dan namespace bernilai karsajobs
metadata:
  name: mongo-secret
  namespace: karsajobs
# Menentukan jenis dari Secret yang dibuat yaitu Opaque
type: Opaque
# Menyimpan data terkait MONGO_ROOT_USERNAME dan MONGO_ROOT_PASSWORD dalam bentuk base64 encoded
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==