# Mengatur versi Kubernetes API yang digunakan untuk membuat object dari manifest yaitu v1
apiVersion: v1
# Mengatur jenis object yang dibuat yaitu Service
kind: Service
# Mengatur nama dari object service yang dibuat yaitu shipping-service
# dan label untuk mengorganisasi object yaitu key app dengan value e-commerce
metadata:
  labels:
    app: e-commerce
  name: shipping-service
# Mengatur spesifikasi dari object meliputi port yang diekspos adalah 3001,
# menggunakan selector app: e-commerce dan tier shipping serta memakai tipe NodePort
spec:
  ports:
  - port: 3001
  selector:
    app: e-commerce
    tier: shipping
  type: NodePort